- src: "https://github.com/Stouts/Stouts.locale"
  name: locale
  version: 1.1.0

- src: "https://github.com/Stouts/Stouts.timezone"
  name: timezone
  version: 2.2.0

- src: "https://github.com/Stouts/Stouts.apt"
  name: apt
  version: 1.4.0

- src: "https://github.com/ANXS/postgresql"
  name: postgresql

- src: "https://github.com/geerlingguy/ansible-role-redis"
  name: redis
  version: 1.2.0

- src: "https://github.com/khusnetdinov/provision.ruby"
  name: ruby

- src: "https://github.com/Stouts/Stouts.elasticsearch"
  name: elasticsearch

